### PR TITLE
Obs names

### PR DESCRIPTION
**Pull request by auggiemarignier**
Adds a table with the list of instrument names.  Status to be updated manually.
Creates a news item that links to the table page.

Also addresses #17 to fix long titles.  Just adds some padding.

### CODE REVIEW

**Comment by auggiemarignier** [comment]
For the station status updates, no need to open a new pull request as it is just a minor change.  Administrator can push straight to main.

**Review by anamgferreira — COMMENTED** [review]
Hey @auggiemarignier, this is good, but I think that I prefer to have one single news item about the first OBS deployed, and then have another one later on about all the others and the naming process. Is that OK for you? I'm just about to submit my News item about the first one. Then, I'll draft a news item about the press release and press coverage, and then we can come back to the naming competition and announce all the winners?

**Comment by auggiemarignier** [comment]
@anamgferreira sure but we're really starting to have a lot of overlap between the news and blog posts. @dschlaphorst has already done a blog about the first station that is currently under review #29

**Review by anamgferreira — APPROVED** [review]

**Comment by anamgferreira** [comment]
All good!

**Pull request merged**
