### PR TITLE
DEPAS-OBSs

### PR DESCRIPTION
**Pull request by Thea92**
Hi,
this is the blog entry about the DEPAS-OBSs. Please let me know, if there is something to change or whatever.

### CODE REVIEW

**Comment by Thea92** [comment]
> Hi,
> this is the blog entry about the DEPAS-OBSs. Please let me know, if there is something to change or whatever.

ah, I already found a spelling error.... staff not stuff..... :-D
How can I change that now?

**Comment by auggiemarignier** [comment]
Content is good! Just a few things to get the images working

1. save the image files in the `static` folder.  Create a new folder in `static` called `blogs`.
2. use Hugo's figure functionality rather than pure markdown https://gohugo.io/content-management/shortcodes/#example-figure-input
3. put your name in the `author` bit at the top of your markdown file :)

**Comment by auggiemarignier** [comment]
Also add a short summary in the summary section at the top of the markdown file

**Review by auggiemarignier — COMMENTED** [review]
happy

**Review by auggiemarignier — APPROVED** [review]
happy

**Comment by Thea92** [comment]
happy

**Pull request merged**
