### PR TITLE
captain interview

### PR DESCRIPTION
**Pull request by PeterMakus**
interview with the captain

### CODE REVIEW

**Comment by PeterMakus** [comment]
added another interview with José Delgado

**Comment by auggiemarignier** [comment]
@PeterMakus the captain's interview is missing the Portuguese translation.  Please check with Marta and let me know when it's done

**Comment by PeterMakus** [comment]
Coming soon!

**Comment by PeterMakus** [comment]
@auggiemarignier , could you merge this. I added Marta's translation to Portuguese in commit a17ec7b.
Cheers

**Review by auggiemarignier — APPROVED** [review]

**Pull request merged**
